server {
    listen 80;
    server_name localhost;

    # Diretório raiz com os arquivos estáticos compilados
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Configuração explícita do tipo MIME para arquivos WebAssembly
    include /etc/nginx/mime.types;
    types {
        application/wasm wasm;
    }

    # Cache agressivo e controle de cache para assets estáticos em produção (incluindo .wasm)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|wasm)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Páginas de erro padrão
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
